services:
  app:
    container_name: toys-api
    build: .
    volumes:
      - .:/app
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/toysdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: docker
    networks:
      - toys-network


  db:
    container_name: db
    image: postgres:17
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    restart: always
    tty: true
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=toysdb
      - POSTGRES_PASSWORD=docker
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - toys-network

networks:
  toys-network:
    driver: bridge